### ISSUE TITLE
Writing to a file outside the vault

### ISSUE THREAD

**Issue by niniack** [AndreasThinks/obsidian-to-quarto-exporter#1]
Thanks for putting together this plugin! 

I wanted to ask if you would be open to considering a setting that can read the output folder path as an absolute path, as opposed to the current approach which always interprets it as a relative path?

My experience, but this may not be an intuitive approach, is that if the directory is specified with a leading `/`, then it is interpreted as absolute. If it is not specified with a leading `/`, then it is relative. 

Alternatively, there could also be a radio button that specifies whether the output folder path is relative or absolute.

Either way, if this is something you are open to, that would be great! And if you're lacking the bandwidth, I can try and submit a PR based on the approach you prefer. (although it will take me a minute to figure out the ropes of Obsidian plugin building)

**Comment by AndreasThinks** [comment]
Honestly, totally open to this approach, as exporting directly into my quarto website would make a lot of sense, thought I don't know if it might lead to any permission issues?  I think by default, obsidian doesn't write outside the vault, though I'm sure it's doable...Either way, worth a try. I'll have a think, but very welcome to try and do a PR in the interim!

**Comment by niniack** [comment]
I'm dropping this here just for both of our references! 

Here's a Quarto plugin that exports things to outside the vault: https://github.com/bingryan/obsidian-markdown-export-plugin

**Comment by AndreasThinks** [comment]
Fixed in 1.0.5!
